FRONTENDSCHOOL6/WonT

- package.json
- pnpm-lock.yaml
- src/components/main/MainMakePlan.jsx
- src/components/main/MainPlace.jsx
- src/components/main/MainTravels.jsx
- src/pages/LandingPage.jsx
- src/pages/MainPage.jsx
- src/routes.jsx
- src/utils/getPocketHostURL.js
> Main page 랜더링완성, 반응형 구현

- src/components/PageHeader.jsx
- src/components/TripPlan.jsx
- src/components/main/MainPlace.jsx
- src/components/mypage/BookmarkList.jsx
- src/components/mypage/PlanPreview.jsx
- src/pages/DetailPage.jsx
- src/pages/MyPage/BookmarkPage.jsx
- src/pages/MyPage/MySchedule.jsx
- src/pages/TravelsPage.jsx
- src/pages/TripEditPage.jsx
- tailwind.config.js
style : Trip 관련 페이지 여행 일정 부분 스타일 수정
feat : MySchedule 아이디에 따른 일정 데이터 렌더링 / BookmarkPage 이미지 리스트 반응형 이슈 해결
feat : 로그인 유저에 따른 북마크 기능 구현중
> My page 기능 구현 진행 중

- src/components/Map.jsx
- src/components/MapCategory.jsx
- src/components/MapSearch.jsx
- src/components/Spinner/Spinner.jsx
- src/components/TripPlan.jsx
- src/components/TripSelect/TripPlanMenu.jsx
- src/pages/TripEditPage.jsx
- src/pages/TripPlacePage.jsx
- src/store/dateStore.js
- src/store/mapStore.js
- 컴포넌트 props 수정
- map 카테고리별 장소 구현 작업 중
> Trip calendar page - 컴포넌트 정리 및 Map 카테고리 기능 구현

- src/components/main/MainHeader.jsx
- src/components/main/MainPlace.jsx
- src/components/main/MainTravels.jsx
- src/pages/MainPage.jsx
> [fix] MainPage 경로 변경

- src/components/Logo.jsx
- src/components/MyPage/PlanPreview.jsx
- src/contexts/Auth.jsx
- src/main.jsx
- src/pages/LandingPage.jsx
- src/pages/SignInPage.jsx
- src/pages/SignUpPage.jsx
LandingPage , SignInPage , SignUpPage 성능 개선 및 접근성 개선
> [page] 성능개선 및 접근성 개선

- src/components/Map.jsx
- src/components/MyPage/BookmarkList.jsx
- src/components/MyPage/MyPageTab.jsx
- src/components/MyPage/PlanPreview.jsx
- src/components/PageHeader.jsx
- src/pages/DetailPage.jsx
- src/pages/MyPage/BookmarkPage.jsx
- src/pages/MyPage/MySchedule.jsx
- src/store/bookmarkStore.js
- tailwind.config.js
style : tailwind.config 애니메이션 추가 / 헤더 사이즈 수정 완료
feat : 북마크 기능 구현 수정 완료
> [Detail | MyShedule | Bookmark] 기능구현 및 스타일 수정

- src/components/Map.jsx
- src/components/TripSelect/MapHotel.jsx
- src/components/TripSelect/MapPlace.jsx
- src/pages/TripHotelPage.jsx
- src/pages/TripPlacePage.jsx
- src/routes.jsx
- src/store/mapStore.js
comment: 불필요한 주석 삭제
feat: Map 기능 분리 - id 및 store 수정
> Map api 기능 정리

- src/components/MyPage/BookmarkList.jsx
- src/components/MyPage/MyPageTab.jsx
- src/components/MyPage/MyPageTabInfo.jsx
- src/components/MyPage/PlanPreview.jsx
- src/components/PageHeader.jsx
- src/pages/DetailPage.jsx
- src/pages/MyPage/BookmarkPage.jsx
- src/pages/MyPage/MySchedule.jsx
- src/pages/TravelsPage.jsx
- src/styles/tailwind.css
- tailwind.config.js
feat : 애니메이션 수정
fix : 가로 스크롤 및 반응형 헤더 깨짐 수정
> [MySchedule | Bookmark | Travels] 애니메이션 수정 및 반응형 깨짐 수정

- src/components/Main/MainPlace.jsx
- src/store/bookmarkStore.js
> [Main page] 북마크 버튼 기능 구현

- src/App.jsx
- src/components/Main/MainMakePlan.jsx
- src/components/Map.jsx
- src/components/MyPage/PlanPreview.jsx
- src/components/PageHeader.jsx
- src/components/TripPlan.jsx
- src/pages/DetailPage.jsx
- src/pages/MyPage/BookmarkPage.jsx
- src/pages/MyPage/MySchedule.jsx
- src/pages/TravelsPage.jsx
- src/pages/TripEditPage.jsx
- tailwind.config.js
[TripEdit] 선택한 여행 정보 데이터 렌더링 진행중
> [TripEdit] 선택한 여행 정보 데이터 렌더링 진행중

- src/components/TripLocal/LocalImage.jsx
- src/components/TripLocal/LocalItem.jsx
- src/pages/TripLocalPage.jsx
> feat, fix: 지역 선택 후 취소 기능 구현 및 최적화

- src/components/TripCalendar/TripCalendar.jsx
- src/pages/TripCalendarPage.jsx
- 달력 네비게이션 형식 함수 리렌더링 버그 해결
- 달력과 버튼 사이 적절한 여백 주기
> fix: 리렌더링 방지 및 적절한 여백 주기

- src/components/Map.jsx
- src/components/TripEdit/PlanDate.jsx
- src/components/TripEdit/SelectHotelMap.jsx
- src/components/TripEdit/TripSchedule.jsx
- src/components/TripPlan.jsx
- src/pages/TripEditPage.jsx
- src/store/markerStore.js
- src/store/selectRangeStore.js
- src/utils/getRangeDay.js
- tailwind.config.js
[TripEdit] 저장된 마커 지도에 표시 및 일정 정보렌더링
> [TripEdit] 저장된 마커 지도에 표시 및 일정 정보렌더링

- src/components/TripSelect/AddButton.jsx
- src/components/TripSelect/AddPlaceItem.jsx
- src/components/TripSelect/AddPlaceItemContent.jsx
- src/components/TripSelect/CheckIcon.jsx
- src/components/TripSelect/TripPlaceItem.jsx
- src/pages/TripHotelPage.jsx
- src/store/mapStore.js
- src/store/scheduleStore.js
- 숙소 선택시 추가 버튼 -> 확인 버튼으로 변경하기
- 장소 추가시 추가 항목창에 렌더링 (최대 3개까지 `overflow-y-scroll`)
- 선택한 숙소 없을 시 기본 문구 출력하기
> feat: TripHotelPage - 숙소 선택 및 추가 항목 렌더링 

- src/components/MyScheduleDetail/TotalScheduleView.jsx
- src/components/TripEdit/PlanDate.jsx
- src/components/TripPlan.jsx
- src/components/TripSelect/AddButton.jsx
- src/components/TripSelect/TripPlaceItem.jsx
- src/pages/MyScheduleDetailPage.jsx
- src/pages/TripCalendarPage.jsx
- src/pages/TripEditPage.jsx
- src/pages/TripHotelPage.jsx
- src/pages/TripLocalPage.jsx
- src/routes.jsx
- src/store/scheduleStore.js
- src/utils/getTripDate.js
- src/utils/index.js
- src/utils/updateRecord.js
feat: TripLocal, TripCalendar flow 정리
Map & Select Page : flow 완료
> Map & Select Page flow 작업 완료

- src/components/Main/MainHeader.jsx
- src/components/Main/MainMakePlan.jsx
- src/components/Main/MainPlace.jsx
- src/components/PageHeader.jsx
- src/components/TripPlan.jsx
- src/pages/TravelsPage.jsx
- src/pages/TripLocalPage.jsx
> [TripEdit] 데이터 렌더링 및 업데이트 진행중

- README.md
> [docs] readme 완료

- src/components/TripEdit/ButtonMedium.jsx
- src/components/TripEdit/PlacePlan.jsx
- src/components/TripEdit/PlanDate.jsx
- src/components/TripEdit/SelectHotelMap.jsx
- src/pages/TripEditPage.jsx
- src/pages/TripPlacePage.jsx
- src/store/scheduleStore.js
- src/store/tripScheduleStore.js
[TripEdit] 버튼을 통한 데이터 업데이트 및 삭제 구현 진행중
> [TripEdit] 버튼을 통한 데이터 업데이트 및 삭제 구현 진행중

- src/components/TripPlan.tsx
- src/pages/TripEditPage.tsx
- src/store/dateStore.ts
> refactor : dateStore 코드 수정 및 적용

- src/components/TripPlan.tsx
- src/pages/TripEditPage.tsx
- src/store/dateStore.ts
> Revert "refactor : dateStore 코드 수정 및 적용"

- src/assets/trip/check.svg
- src/assets/trip/plus.svg
- src/components/TripSelect/AddButton.tsx
- src/components/TripSelect/HambugerButton.tsx
- src/components/TripSelect/MapHotel.tsx
- src/components/TripSelect/MapPlace.tsx
- src/components/TripSelect/TripHotelItem.tsx
- src/components/TripSelect/TripPlaceItem.tsx
- src/components/TripSelect/TripPlanMenu.tsx
- src/pages/TripHotelPage.tsx
- src/pages/TripLocalPage.tsx
- src/pages/TripPlacePage.tsx
- src/types/Recommends.ts
- src/utils/debounce.ts
- src/utils/getPocketHostImageURL.ts
> Ts/triphotelplace: 여행지 놀거리, 숙소 선택 페이지

- src/assets/trip/check.svg
- src/assets/trip/plus.svg
- src/components/TripLocal/LocalImage.tsx
- src/components/TripLocal/LocalItem.tsx
- src/components/TripSelect/AddButton.tsx
- src/components/TripSelect/HambugerButton.tsx
- src/components/TripSelect/MapHotel.tsx
- src/components/TripSelect/MapPlace.tsx
- src/components/TripSelect/TripHotelItem.tsx
- src/components/TripSelect/TripPlaceItem.tsx
- src/components/TripSelect/TripPlanMenu.tsx
- src/pages/TripHotelPage.tsx
- src/pages/TripLocalPage.tsx
- src/pages/TripPlacePage.tsx
- src/types/Recommends.ts
- src/utils/debounce.ts
- src/utils/getPocketHostImageURL.ts
> Ts/triplocal: 여행지 선택 페이지

- src/components/TripLocal/LocalImage.tsx
- src/components/TripLocal/LocalItem.tsx
- src/components/TripPlan.tsx
- src/pages/TripCalendarPage.tsx
> Ts/calendar: 여행 날짜 선택 페이지

- index.html
- src/components/Landing/Sns.tsx
- src/components/Main/MainMakePlan.tsx
- src/components/MyPage/PlanPreview.tsx
- src/components/MyScheduleDetail/TotalScheduleSummary.tsx
- src/components/Sign/BackButton.tsx
- src/components/TripEdit/PlanDate.tsx
> fix: 경로명 수정

- src/components/Detail/DetailInfo.tsx
- src/components/MyPage/BookmarkList.tsx
- src/components/MyPage/PlanPreview.tsx
- src/pages/DetailPage.tsx
- src/pages/MyPage/MySchedule.tsx
- src/pages/TravelsPage.tsx
- src/types/DetailPage.ts
- src/types/MySchedule.ts
- src/types/Travels.ts
- src/utils/getPocketHostImageURL.ts
- 타입 오류 해결
- any 타입 일부 해결
- 이미지 렌더링 이슈 해결
---
---
> fix : 이미지 렌더링 오류 및 타입 오류 해결

- src/components/TripCalendar/TripCalendar.tsx
- src/pages/TripCalendarPage.tsx
- 달력 type 오류로 페이지 미출력 부분 주석 처리
- 추후 달력 수정 후 반영 예정
---
>  bug: 여행 날짜 선택 페이지 - 날짜 주석 처리
